"""Generate the bridge contract without runtime file IO. Run with --check in CI."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import pprint

ROOT = Path(__file__).resolve().parents[1]


def generate():
    profile = json.loads((ROOT / "profiles/guanjie-v1.json").read_text())
    assert profile["read_only"] is True
    # These are reviewed v1 firmware invariants, not editable capability expansion.
    assert profile["bridge_version"] == 1
    limits = profile["limits"]
    assert (
        limits["slave_min"],
        limits["slave_max"],
        limits["register_count"],
        limits["timeout_ms"],
    ) == (1, 32, 1, 700)
    assert limits["polling_pause_required"] is True
    registers = profile["allowed_registers"]
    assert len(registers) == len(set(registers)) == 13
    # Normal control telemetry indexes this layout; reordering is not innocuous.
    assert registers == [
        0x6201,
        0x6202,
        0x6203,
        0x6205,
        0x6206,
        0x6105,
        0x6101,
        0x6102,
        0x6103,
        0x6104,
        0x6106,
        0x6111,
        0x6112,
    ]
    assert all(type(r) is int and 0 <= r <= 65535 for r in registers)
    assert profile["defaults"]["register_address"] in registers
    assert profile["defaults"]["probe_type"] == "holding_register"
    canonical = json.dumps(profile, sort_keys=True, separators=(",", ":")).encode()
    profile["profile_hash"] = hashlib.sha256(canonical).hexdigest()
    py = "# Generated by tools/generate_profiles.py; edit profiles/guanjie-v1.json.\n"
    py += "PROFILE = " + pprint.pformat(profile, sort_dicts=False, width=88) + "\n"
    js = "// Generated by tools/generate_profiles.py; do not edit.\n"
    js += (
        'const freeze = value => { if (value && typeof value === "object") '
        "{Object.values(value).forEach(freeze); Object.freeze(value);} return value; };\n"
    )
    js += "export const PHYSICAL_PROFILE = freeze(" + json.dumps(profile, indent=2) + ");\n"
    h = (
        "// Generated by tools/generate_profiles.py; do not edit.\n#pragma once\n"
        "#include <array>\n#include <cstdint>\nnamespace esphome::guanjie::bridge_profile {\n"
    )
    h += f'inline constexpr char HASH[] = "{profile["profile_hash"]}";\n'
    h += f"inline constexpr uint8_t SLAVE_MAX = {profile['limits']['slave_max']};\n"
    h += (
        "inline constexpr std::array<uint16_t, 13> REGISTERS = {"
        + ", ".join(f"0x{r:04X}" for r in registers)
        + "};\n}\n"
    )
    return {
        "custom_components/woow_esphome_modbus_scanner/modbus_scan/profile_generated.py": py,
        "panel_frontend/src/profile-generated.js": js,
        "firmware/guanjie-scanner/components/guanjie/profile_generated.h": h,
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in generate().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Generated profile drift: {name}")
        else:
            path.write_text(content)
    print("Generated profiles are current." if args.check else "Generated three bridge profiles.")


if __name__ == "__main__":
    main()
